// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuZJexWXpkAI_sG2VxVVxiJhMsOQQ7Ubs',
    appId: '1:78592403770:web:55178219fe3956d260c803',
    messagingSenderId: '78592403770',
    projectId: 'mysp-demo-b2396',
    authDomain: 'mysp-demo-b2396.firebaseapp.com',
    storageBucket: 'mysp-demo-b2396.appspot.com',
    measurementId: 'G-QZR2VVVHM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkGy1QmtGn9t76z9MV7POKI9LNwQb_v08',
    appId: '1:78592403770:android:ccd9490203acf03660c803',
    messagingSenderId: '78592403770',
    projectId: 'mysp-demo-b2396',
    storageBucket: 'mysp-demo-b2396.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPoDMHQnK98i644XaMSynoRZjAmy2twsA',
    appId: '1:78592403770:ios:1dc83be40edf117560c803',
    messagingSenderId: '78592403770',
    projectId: 'mysp-demo-b2396',
    storageBucket: 'mysp-demo-b2396.appspot.com',
    iosBundleId: 'com.example.exYtLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPoDMHQnK98i644XaMSynoRZjAmy2twsA',
    appId: '1:78592403770:ios:f8514f899ad5ddb560c803',
    messagingSenderId: '78592403770',
    projectId: 'mysp-demo-b2396',
    storageBucket: 'mysp-demo-b2396.appspot.com',
    iosBundleId: 'com.example.exYtLogin.RunnerTests',
  );
}
